#pragma once
#define FLUXUI_FAST_STARTUP 1
#define FLUXUI_SHOW_WINDOW_ON_INIT 0
#define FLUXUI_REVEAL_WINDOW_ON_FIRST_FRAME 1
#define FLUXUI_PREALLOC_WIDGETS 512
#define FLUXUI_PREALLOC_TEXT_NODES 1024
#define FLUXUI_PREALLOC_PANELS 256
#define FLUXUI_PREALLOC_ROOT_CHILDREN 16
#define FLUXUI_PREALLOC_ROUTES 24
#define FLUXUI_PREALLOC_EVENT_LISTENERS 32
#define FLUXUI_PREALLOC_FONTS 32
#define FLUXUI_PREALLOC_IMAGES 96
#define FLUXUI_PREALLOC_SCISSORS 16
#define FLUXUI_PREALLOC_TRANSFORMS 16
#define FLUXUI_PREALLOC_RECT_BATCH 512
#define FLUXUI_PREALLOC_TEXT_FLOATS 16384
#define FLUXUI_IMMEDIATE_RENDER 1
#define FLUXUI_STYLE_CACHE_SIZE 4096
#define FLUXUI_TEXT_MEASURE_CACHE_SIZE 8192
#define FLUXUI_OPTIMIZE_LAYOUT 1
#define FLUXUI_MINIMAL_ALLOCS 1
#define FLUXUI_GPU_OPTIMIZE 1
#define FLUXUI_TARGET_FPS 120
#ifndef _DEBUG
#define FLUXUI_SILENT_STARTUP 1
#endif
