# FluxUI Auto File-Based Routing (like Next.js pages/)
#
# Usage in CMakeLists.txt:
#   include(cmake/AutoRoutes.cmake)
#   fluxui_auto_routes(
#       TARGET      my_app
#       VIEWS_DIR   "${CMAKE_CURRENT_SOURCE_DIR}/views"
#       OUTPUT      "${CMAKE_BINARY_DIR}/generated/routes_gen.h"
#       NAMESPACE   myapp
#   )
#
# Convention:
#   views/dashboard.h  →  route "/dashboard"  →  calls myapp::DashboardView()
#   views/settings.h   →  route "/settings"   →  calls myapp::SettingsView()
#   views/user_profile.h → route "/user-profile" → calls myapp::UserProfileView()
#
# Each view file must define:
#   namespace myapp { inline fluxui::Element XxxView() { return ...; } }
#
function(fluxui_auto_routes)
    cmake_parse_arguments(ARG "" "TARGET;VIEWS_DIR;OUTPUT;NAMESPACE" "" ${ARGN})

    if(NOT ARG_VIEWS_DIR OR NOT ARG_OUTPUT OR NOT ARG_NAMESPACE)
        message(FATAL_ERROR "fluxui_auto_routes requires TARGET, VIEWS_DIR, OUTPUT, and NAMESPACE")
    endif()

    # Scan for view headers at configure time.
    file(GLOB VIEW_FILES "${ARG_VIEWS_DIR}/*.h")

    # Generate the routes header.
    set(GEN_INCLUDES "")
    set(GEN_REGISTRATIONS "")

    foreach(VIEW_FILE ${VIEW_FILES})
        get_filename_component(VIEW_NAME "${VIEW_FILE}" NAME_WE) # e.g. "dashboard"

        # Convert snake_case filename to PascalCase function name.
        string(REPLACE "_" ";" PARTS "${VIEW_NAME}")
        set(PASCAL "")
        foreach(PART ${PARTS})
            string(SUBSTRING "${PART}" 0 1 FIRST)
            string(TOUPPER "${FIRST}" FIRST)
            string(SUBSTRING "${PART}" 1 -1 REST)
            string(APPEND PASCAL "${FIRST}${REST}")
        endforeach()

        # Convert to route path: underscores become hyphens.
        string(REPLACE "_" "-" ROUTE_PATH "${VIEW_NAME}")

        string(APPEND GEN_INCLUDES "#include \"${VIEW_FILE}\"\n")
        string(APPEND GEN_REGISTRATIONS "    app.addRoute(\"/${ROUTE_PATH}\", ${ARG_NAMESPACE}::${PASCAL}View);\n")
    endforeach()

    # Write the generated header.
    # The first route alphabetically or "index" becomes the default.
    set(DEFAULT_ROUTE "")
    foreach(VIEW_FILE ${VIEW_FILES})
        get_filename_component(VNAME "${VIEW_FILE}" NAME_WE)
        if(VNAME STREQUAL "index")
            string(REPLACE "_" "-" ROUTE_PATH "${VNAME}")
            set(DEFAULT_ROUTE "/${ROUTE_PATH}")
            break()
        endif()
    endforeach()
    if(NOT DEFAULT_ROUTE AND VIEW_FILES)
        list(GET VIEW_FILES 0 FIRST_VIEW)
        get_filename_component(FNAME "${FIRST_VIEW}" NAME_WE)
        string(REPLACE "_" "-" DEFAULT_ROUTE "/${FNAME}")
    endif()

    file(WRITE "${ARG_OUTPUT}"
        "// Auto-generated file-based routes (like Next.js pages/)\n"
        "// DO NOT EDIT — regenerated by CMake on configure.\n"
        "#pragma once\n\n"
        "${GEN_INCLUDES}\n"
        "namespace ${ARG_NAMESPACE} {\n"
        "namespace generated {\n\n"
        "inline void registerRoutes(fluxui::App& app) {\n"
        "${GEN_REGISTRATIONS}"
        "}\n\n"
        "inline const char* defaultRoute() { return \"${DEFAULT_ROUTE}\"; }\n\n"
        "} // namespace generated\n"
        "} // namespace ${ARG_NAMESPACE}\n"
    )

    # Tell CMake to re-configure if the views directory changes.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ARG_VIEWS_DIR}")

    # Add include directory so the target can find the generated header.
    if(ARG_TARGET)
        get_filename_component(GEN_DIR "${ARG_OUTPUT}" DIRECTORY)
        target_include_directories(${ARG_TARGET} PRIVATE "${GEN_DIR}")
    endif()
endfunction()
