// FluxUI build/runtime tuning defaults.
#pragma once

#ifndef FLUXUI_FAST_STARTUP
#define FLUXUI_FAST_STARTUP 1
#endif

#ifndef FLUXUI_SHOW_WINDOW_ON_INIT
#define FLUXUI_SHOW_WINDOW_ON_INIT 0
#endif

#ifndef FLUXUI_REVEAL_WINDOW_ON_FIRST_FRAME
#define FLUXUI_REVEAL_WINDOW_ON_FIRST_FRAME 1
#endif

#ifndef FLUXUI_SILENT_STARTUP
#if defined(NDEBUG)
#define FLUXUI_SILENT_STARTUP 1
#else
#define FLUXUI_SILENT_STARTUP 0
#endif
#endif

#ifndef FLUXUI_PREALLOC_WIDGETS
#define FLUXUI_PREALLOC_WIDGETS 512
#endif

#ifndef FLUXUI_PREALLOC_TEXT_NODES
#define FLUXUI_PREALLOC_TEXT_NODES 1024
#endif

#ifndef FLUXUI_PREALLOC_PANELS
#define FLUXUI_PREALLOC_PANELS 256
#endif

#ifndef FLUXUI_PREALLOC_ROOT_CHILDREN
#define FLUXUI_PREALLOC_ROOT_CHILDREN 16
#endif

#ifndef FLUXUI_PREALLOC_ROUTES
#define FLUXUI_PREALLOC_ROUTES 24
#endif

#ifndef FLUXUI_PREALLOC_EVENT_LISTENERS
#define FLUXUI_PREALLOC_EVENT_LISTENERS 32
#endif

#ifndef FLUXUI_PREALLOC_FONTS
#define FLUXUI_PREALLOC_FONTS 32
#endif

#ifndef FLUXUI_PREALLOC_IMAGES
#define FLUXUI_PREALLOC_IMAGES 96
#endif

#ifndef FLUXUI_PREALLOC_SCISSORS
#define FLUXUI_PREALLOC_SCISSORS 16
#endif

#ifndef FLUXUI_PREALLOC_TRANSFORMS
#define FLUXUI_PREALLOC_TRANSFORMS 16
#endif

#ifndef FLUXUI_PREALLOC_RECT_BATCH
#define FLUXUI_PREALLOC_RECT_BATCH 512
#endif

#ifndef FLUXUI_PREALLOC_TEXT_FLOATS
#define FLUXUI_PREALLOC_TEXT_FLOATS 16384
#endif

#ifndef FLUXUI_STYLE_CACHE_SIZE
#define FLUXUI_STYLE_CACHE_SIZE 4096
#endif

#ifndef FLUXUI_TEXT_MEASURE_CACHE_SIZE
#define FLUXUI_TEXT_MEASURE_CACHE_SIZE 8192
#endif

#ifndef FLUXUI_OPTIMIZE_LAYOUT
#define FLUXUI_OPTIMIZE_LAYOUT 1
#endif

#ifndef FLUXUI_MINIMAL_ALLOCS
#define FLUXUI_MINIMAL_ALLOCS 1
#endif

#ifndef FLUXUI_GPU_OPTIMIZE
#define FLUXUI_GPU_OPTIMIZE 1
#endif

#ifndef FLUXUI_LOW_MEMORY
#define FLUXUI_LOW_MEMORY 0
#endif

#ifndef FLUXUI_VULKAN_RETAINED_DYNAMIC_PAGES
#if FLUXUI_LOW_MEMORY
#define FLUXUI_VULKAN_RETAINED_DYNAMIC_PAGES 1
#else
#define FLUXUI_VULKAN_RETAINED_DYNAMIC_PAGES 4
#endif
#endif

#ifndef FLUXUI_TARGET_FPS
#define FLUXUI_TARGET_FPS 120
#endif
